export interface MeteoraPoolSignal {
  poolAddress: string;
  pairName: string;
  binStep: number;
  baseFeePercentage: number;
  tvlUsd: number;
  activeTvlUsd: number; // Active TVL inside current bin price range
  volume4hUsd: number;  // 4-hour rolling trading volume
  fee4hUsd: number;     // Fees generated in the last 4 hours
  fees24hSol: number;   // Total accumulated fees in the last 24h in SOL (Meridian minimum check)
  feeAprPercentage: number;
  feesToTvlRatio4h: number; // 4-hour Fees / TVL ratio (Meridian multihour yield metric)
  volumeToTvlRatio4h: number; // 4-hour Volume / Total TVL ratio (Overall pool popularity)
  volumeToActiveTvlRatio4h: number; // 4-hour Volume / Active TVL ratio (Capital velocity metric)
  organicVolumeScore4h: number; // Organic activity score for 4h window (0-100)
  tokenAgeMinutes?: number;
  recommendedDistribution: 'Spot' | 'Curve' | 'Bid-Ask';
  aiRecommendation: string;
}

export class MeteoraDLMMAdapter {
  private apiEndpoint = 'https://dlmm-api.meteora.ag';

  public async fetchTopYieldPools(minTvlUsd: number = 5000): Promise<MeteoraPoolSignal[]> {
    try {
      // Sample pools incorporating 4-hour stable multihour yield & capital velocity metrics
      const samplePools: MeteoraPoolSignal[] = [
        {
          poolAddress: 'AR1mtav29Ym5snyY7zBms4A2kUqtjU2vB5nK',
          pairName: 'SOL-USDC (Meteora DLMM)',
          binStep: 10,
          baseFeePercentage: 0.25,
          tvlUsd: 150000,
          activeTvlUsd: 25000,
          volume4hUsd: 145000,
          fee4hUsd: 362.5,
          fees24hSol: 10.2, // 10.2 SOL fees generated in 24h (passes >= 5 SOL check)
          feeAprPercentage: 529.0,
          feesToTvlRatio4h: 0.0024,
          volumeToTvlRatio4h: 0.96,
          volumeToActiveTvlRatio4h: 5.8,
          organicVolumeScore4h: 90,
          tokenAgeMinutes: 43200,
          recommendedDistribution: 'Spot',
          aiRecommendation: 'Stable multihour volume efficiency. Recommended Spot LP setting.',
        },
        {
          poolAddress: '7xKXtg2CW87d9X83M1qP829X83M1qP829X83M',
          pairName: 'SOL-BONK (Meteora DLMM)',
          binStep: 25,
          baseFeePercentage: 1.0,
          tvlUsd: 45000,
          activeTvlUsd: 8000,
          volume4hUsd: 68000,
          fee4hUsd: 680,
          fees24hSol: 19.4, // 19.4 SOL fees in 24h
          feeAprPercentage: 2750.0,
          feesToTvlRatio4h: 0.0151,
          volumeToTvlRatio4h: 1.51,
          volumeToActiveTvlRatio4h: 8.5,
          organicVolumeScore4h: 82,
          tokenAgeMinutes: 10080,
          recommendedDistribution: 'Curve',
          aiRecommendation: 'High dynamic fee capture. Use Curve distribution to harvest high volatility yields.',
        },
        {
          poolAddress: 'FakEPoOL87d9X83M1qP829X83M1qP829X83MF',
          pairName: 'SOL-SHITCOIN (Meteora DLMM)',
          binStep: 100,
          baseFeePercentage: 2.0,
          tvlUsd: 12000,
          activeTvlUsd: 1500,
          volume4hUsd: 15000,
          fee4hUsd: 300,
          fees24hSol: 1.4, // REJECTED: Only 1.4 SOL fees (does not pass >= 5 SOL check)
          feeAprPercentage: 5475.0,
          feesToTvlRatio4h: 0.025,
          volumeToTvlRatio4h: 1.25,
          volumeToActiveTvlRatio4h: 10.0,
          organicVolumeScore4h: 20,
          tokenAgeMinutes: 45,
          recommendedDistribution: 'Bid-Ask',
          aiRecommendation: 'Deceptive volume generated by wash-trading bots on a new launch. High risk of rugpull.',
        },
      ];

      return samplePools.filter(p => p.tvlUsd >= minTvlUsd);
    } catch (err: any) {
      console.error('[METEORA DLMM ADAPTER ERROR]', err.message);
      return [];
    }
  }

  /**
   * Applies Aggressive Trade + LP Velocity screening rules tailored to a 4-hour window on Solana (Meteora DLMM)
   */
  public filterHighYieldPools(pools: MeteoraPoolSignal[]): MeteoraPoolSignal[] {
    return pools.filter(pool => {
      // 1. Min 10 SOL total fees generated by the pool in 24h
      const passesMinFeesSol = pool.fees24hSol >= 10;

      // 2. Min 5.0% (0.05) fee yield per 4-hour period (~30% daily yield / ~10,000%+ APR)
      const passesFeesRatio = pool.feesToTvlRatio4h >= 0.05; 

      // 3. Min 1.5x (150%) Volume to Total TVL ratio in 4 hours
      const passesVolumeToTvl = pool.volumeToTvlRatio4h >= 1.5;

      // 4. Min 6.0x Volume to Active TVL ratio in 4 hours (active range velocity check)
      const passesVolumeVelocity = pool.volumeToActiveTvlRatio4h >= 6.0;
      
      // 5. Min 65% organic trading activity in the last 4 hours (ignores bot manipulation)
      const passesOrganicScore = pool.organicVolumeScore4h >= 65; 
      
      // 6. Min token age of 6 hours (360 minutes) to avoid quick launch rugpulls
      const passesAge = pool.tokenAgeMinutes ? pool.tokenAgeMinutes >= 360 : true; 

      return passesMinFeesSol && passesFeesRatio && passesVolumeToTvl && passesVolumeVelocity && passesOrganicScore && passesAge;
    });
  }
}
